name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: osrm-backend

    steps:
      - uses: actions/checkout@v4

      - name: Set tag
        id: set_tag
        run: echo "tag=$(date +%F)" >> "$GITHUB_OUTPUT"

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t josafaverissimo/osrm-backend-nordeste:$(date +%F) .
          docker push josafaverissimo/osrm-backend-nordeste:$(date +%F)
